const menuButton=document.querySelector('.menu-button');const navigation=document.querySelector('.site-navigation');
if(menuButton&&navigation){menuButton.addEventListener('click',()=>{const o=navigation.classList.toggle('is-open');menuButton.classList.toggle('is-open',o);menuButton.setAttribute('aria-expanded',String(o));});navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navigation.classList.remove('is-open');menuButton.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false');}));}
const tracks=[...document.querySelectorAll('.track')];let autoPlay=false;
function setAuto(v){autoPlay=v;document.querySelectorAll('.autoplay-toggle').forEach(t=>t.checked=v);}
function collapse(track,pause=true){const a=track.querySelector('audio'),b=track.querySelector('.track-play-button');track.classList.remove('is-open');if(pause&&a&&!a.paused)a.pause();if(b){b.textContent='PLAY';b.setAttribute('aria-expanded','false');}}
function openTrack(track){tracks.forEach(t=>{if(t!==track)collapse(t,true)});track.classList.add('is-open');const b=track.querySelector('.track-play-button');if(b){b.textContent='PAUSE';b.setAttribute('aria-expanded','true');}}
tracks.forEach((track,i)=>{const b=track.querySelector('.track-play-button'),a=track.querySelector('audio'),toggle=track.querySelector('.autoplay-toggle');if(!b||!a)return;if(toggle)toggle.addEventListener('change',()=>setAuto(toggle.checked));b.addEventListener('click',async()=>{if(!a.paused){a.pause();collapse(track,false);return;}openTrack(track);try{await a.play();}catch(e){collapse(track,false);}});a.addEventListener('play',()=>openTrack(track));a.addEventListener('pause',()=>{if(!a.ended)collapse(track,false);});a.addEventListener('ended',async()=>{a.currentTime=0;collapse(track,false);if(autoPlay&&tracks.length){const next=tracks[(i+1)%tracks.length],na=next.querySelector('audio');openTrack(next);try{await na.play();}catch(e){collapse(next,false);}}});});
const releaseThumbs=document.querySelectorAll('.release-thumb'),releaseMainImage=document.querySelector('#release-main-image'),releaseTitle=document.querySelector('#release-title'),releaseStatus=document.querySelector('#release-status'),releaseActiveContent=document.querySelector('#release-active-content'),releaseActiveContentTwo=document.querySelector('#release-active-content-006-010'),releaseDevelopmentMessage=document.querySelector('#release-development-message');releaseThumbs.forEach(button=>button.addEventListener('click',()=>{releaseThumbs.forEach(x=>x.classList.remove('is-active'));button.classList.add('is-active');if(releaseMainImage){releaseMainImage.src=button.dataset.image||'';releaseMainImage.alt=button.dataset.title||'ALEXATOR release';}if(releaseTitle)releaseTitle.textContent=button.dataset.title||'';if(releaseStatus)releaseStatus.textContent=button.dataset.status||'';const active=button.dataset.active==='true',content=button.dataset.content||'';if(releaseActiveContent)releaseActiveContent.hidden=!(active&&content==='001-005');if(releaseActiveContentTwo)releaseActiveContentTwo.hidden=!(active&&content==='006-010');if(releaseDevelopmentMessage)releaseDevelopmentMessage.hidden=active;}));
const modalTriggers=document.querySelectorAll('[data-modal]'),modalCloseControls=document.querySelectorAll('[data-close-modal]');function closeMediaModal(m){if(!m)return;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}modalTriggers.forEach(t=>t.addEventListener('click',()=>{const m=document.getElementById(t.dataset.modal);if(!m)return;m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}));modalCloseControls.forEach(c=>c.addEventListener('click',()=>closeMediaModal(c.closest('.media-modal'))));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMediaModal(document.querySelector('.media-modal.is-open'));});document.querySelectorAll('[data-copy-target]').forEach(b=>b.addEventListener('click',async()=>{const t=document.getElementById(b.dataset.copyTarget);if(!t)return;const old=b.textContent;try{await navigator.clipboard.writeText(t.innerText.trim());b.textContent='Copied';}catch(e){b.textContent='Select text manually';}setTimeout(()=>b.textContent=old,1800);}));
