const menuButton=document.querySelector('.menu-button');const navigation=document.querySelector('.site-navigation');
if(menuButton&&navigation){menuButton.addEventListener('click',()=>{const o=navigation.classList.toggle('is-open');menuButton.classList.toggle('is-open',o);menuButton.setAttribute('aria-expanded',String(o));});navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navigation.classList.remove('is-open');menuButton.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false');}));}
const tracks=[...document.querySelectorAll('.track')];let autoPlay=false;
function setAuto(v){autoPlay=v;document.querySelectorAll('.autoplay-toggle').forEach(t=>t.checked=v);}
function collapse(track,pause=true){const a=track.querySelector('audio'),b=track.querySelector('.track-play-button');track.classList.remove('is-open');if(pause&&a&&!a.paused)a.pause();if(b){b.textContent='PLAY';b.setAttribute('aria-expanded','false');}}
function openTrack(track){tracks.forEach(t=>{if(t!==track)collapse(t,true)});track.classList.add('is-open');const b=track.querySelector('.track-play-button');if(b){b.textContent='PAUSE';b.setAttribute('aria-expanded','true');}}
tracks.forEach((track,i)=>{const b=track.querySelector('.track-play-button'),a=track.querySelector('audio'),toggle=track.querySelector('.autoplay-toggle');if(!b||!a)return;if(toggle)toggle.addEventListener('change',()=>setAuto(toggle.checked));b.addEventListener('click',async()=>{if(!a.paused){a.pause();collapse(track,false);return;}openTrack(track);try{await a.play();}catch(e){collapse(track,false);}});a.addEventListener('play',()=>openTrack(track));a.addEventListener('pause',()=>{if(!a.ended)collapse(track,false);});a.addEventListener('ended',async()=>{a.currentTime=0;collapse(track,false);if(autoPlay&&tracks.length){const next=tracks[(i+1)%tracks.length],na=next.querySelector('audio');openTrack(next);try{await na.play();}catch(e){collapse(next,false);}}});});
const releaseThumbs=document.querySelectorAll('.release-thumb'),releaseMainImage=document.querySelector('#release-main-image'),releaseTitle=document.querySelector('#release-title'),releaseStatus=document.querySelector('#release-status'),releasePanels=[...document.querySelectorAll('.release-content-panel')],releaseDevelopmentMessage=document.querySelector('#release-development-message');releaseThumbs.forEach(button=>button.addEventListener('click',()=>{releaseThumbs.forEach(x=>x.classList.remove('is-active'));button.classList.add('is-active');if(releaseMainImage){releaseMainImage.src=button.dataset.image||'';releaseMainImage.alt=button.dataset.title||'ALEXATOR release';}if(releaseTitle)releaseTitle.textContent=button.dataset.title||'';if(releaseStatus)releaseStatus.textContent=button.dataset.status||'';const target=button.dataset.content||'';releasePanels.forEach(panel=>panel.hidden=panel.id!==target);if(releaseDevelopmentMessage)releaseDevelopmentMessage.hidden=Boolean(target);}));
const modalTriggers=document.querySelectorAll('[data-modal]'),modalCloseControls=document.querySelectorAll('[data-close-modal]');function closeMediaModal(m){if(!m)return;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}modalTriggers.forEach(t=>t.addEventListener('click',()=>{const m=document.getElementById(t.dataset.modal);if(!m)return;m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}));modalCloseControls.forEach(c=>c.addEventListener('click',()=>closeMediaModal(c.closest('.media-modal'))));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMediaModal(document.querySelector('.media-modal.is-open'));});document.querySelectorAll('[data-copy-target]').forEach(b=>b.addEventListener('click',async()=>{const t=document.getElementById(b.dataset.copyTarget);if(!t)return;const old=b.textContent;try{await navigator.clipboard.writeText(t.innerText.trim());b.textContent='Copied';}catch(e){b.textContent='Select text manually';}setTimeout(()=>b.textContent=old,1800);}));


/* V10: ALEXATOR Music Videos catalogue */
(()=>{const p=document.querySelector('#featured-video'),bs=[...document.querySelectorAll('.video-select')];if(!p||!bs.length)return;const n=document.querySelector('#featured-video-number'),t=document.querySelector('#featured-video-title'),d=document.querySelector('#featured-video-description'),y=document.querySelector('#featured-youtube-link'),r=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;function a(b,o={}){const i=b.closest('.video-catalogue-item'),num=b.dataset.number||'',title=b.dataset.title||'',desc=b.dataset.description||'',src=b.dataset.src||'',poster=b.dataset.poster||'',yt=b.dataset.youtube||'https://www.youtube.com/@alexatorcom',same=p.currentSrc===src||p.getAttribute('src')===src;bs.forEach(c=>{const x=c===b;c.setAttribute('aria-pressed',String(x));c.closest('.video-catalogue-item')?.classList.toggle('is-active',x)});if(n)n.textContent=num;if(t)t.textContent=title;if(d)d.textContent=desc;if(y)y.href=yt;p.setAttribute('aria-label',`ALEXATOR ${num} — ${title} official music video`);if(!same&&src){p.pause();p.poster=poster;p.src=src;p.load()}else if(poster)p.poster=poster;if(i?.id&&o.updateHash!==false)history.replaceState(null,'',`#${i.id}`);if(o.scrollToPlayer)document.querySelector('.featured-video-frame')?.scrollIntoView({behavior:r?'auto':'smooth',block:'center'})}bs.forEach(b=>b.addEventListener('click',()=>a(b,{scrollToPlayer:true})));const id=window.location.hash.slice(1);if(id){const q=document.querySelector(`#${CSS.escape(id)} .video-select`);if(q)a(q,{updateHash:false,scrollToPlayer:false})}})();
